### ISSUE TITLE
自作キーボードを組み立てる人を観察する配信

### ISSUE THREAD

**Issue by h3y6e** [camphor-/lab#32]
- 積んでいる自作キーボードを完成させる
by @h3y6e

第一回: https://youtu.be/hSD-ctnsvm4
第二回: https://youtu.be/TjF7hOFf4iM
第三回: https://youtu.be/vEaTdXXsTO8

**Comment by honai** [comment]
@h3y6e 右手分楽しみにしてます

**Comment by h3y6e** [comment]
[続](https://youtu.be/TjF7hOFf4iM) と [完](https://youtu.be/vEaTdXXsTO8) を配信・公開しました。完結です。
